# -*- coding: utf-8 -*-
"""schedule_gantt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ne73VBOooOEZYwX-nq-hwTqS9vsFWdlI
"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

df["Task"] = [
    "Project structure design",
    "Implement Feature 1",
    "Implement Feature 2",
    "Develop Feature 3 (ongoing)",
    "Revise project direction",
    "Finalize feature implementation",
    "Complete all features",
    "Code optimization and documentation"
]

fig, ax = plt.subplots(figsize=(10, 6))
for i, row in df.iterrows():
    ax.barh(row["Task"], (row["종료일"] - row["시작일"]).days, left=row["시작일"].toordinal(), color="skyblue", edgecolor="black")

ax.xaxis.set_major_locator(mdates.WeekdayLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter("2024-%m-%d"))
plt.xticks(rotation=45)
plt.xlabel("Date")
plt.ylabel("Task")
plt.title("Project Progress Gantt Chart")

plt.tight_layout()
plt.show()